# Generated by Django 4.0 on 2021-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.CharField(choices=[('ARCH', 'ARCH'), ('BME', 'BME'), ('BIOTECH', 'BIOTECH'), ('CHEM', 'CHEM'), ('CIVIL', 'CIVIL'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EE', 'EE'), ('IT', 'IT'), ('MECH', 'MECH'), ('META', 'META'), ('MINING', 'MINING')], default='ARCH', max_length=20),
        ),
    ]
