# Generated by Django 4.0 on 2021-12-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='semester',
            new_name='branch',
        ),
    ]
