# Generated by Django 4.0 on 2021-12-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_dislike_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
