# Generated by Django 4.0 on 2021-12-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_semester_customuser_branch'),
        ('posts', '0007_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subly', to='users.customuser')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subly', to='posts.comment')),
            ],
        ),
    ]
